### ISSUE TITLE
PHP Warning: Illegal offset type in isset or empty in template.php on line 950

### ISSUE THREAD

**Issue by mipon** [HardeepAsrani/hello-gutenberg#2]
Hi,

I just tried your example plugin on a fresh install WordPress 5.0.3 locally. Only your plugin is activated. Then if I go to Posts -> Add New then, the following warning occurs. 

```
PHP Warning:  Illegal offset type in isset or empty in ...\wp-admin\includes\template.php on line 950
```

`WP_DEBUG` is enabled. Tried with PHP 7.2 and 5.6 and both give the same error.

**Comment by mxswat** [comment]
+1 This is still broken

**Comment by HardeepAsrani** [comment]
Fixed with https://github.com/HardeepAsrani/hello-gutenberg/commit/231d9915faa0f96dd6611e17891c79de51df1cd7

Let me know if it works now @mxswat
